### ISSUE TITLE
Full crash on bad image path

### ISSUE THREAD

**Issue by ad2017gd** [ad2017gd/RainbowTaskbar#10]

**Comment by ad2017gd** [comment]
@zCri maybe you can fix this while you're at it :trollface: 

https://github.com/ad2017gd/RainbowTaskbar/blob/761db0146496901817372a8ab6ad657d6a41ce65/RainbowTaskbar/Configuration/Instructions/ImageInstruction.cs#L59

i guess put this in a try catch

**Comment by zCri** [comment]
Fixed in f0b6e991a2740ff7487aa3dc168b1c164feab904

**Comment by ad2017gd** [comment]
Thanks bro 💋
