### ISSUE TITLE
Win Taskleiste -Tool

### ISSUE THREAD

**Issue by ErolCel** [ad2017gd/RainbowTaskbar#28]
Hi there, no more clear type appearance since last Windows 11 Update last week. Best regards, ErolCel

**Comment by ad2017gd** [comment]
Fixed in 2.3.1 (e918aa5)

**Comment by ad2017gd** [comment]
by the way, you are another victim of the fake windows store entry for this app. i suggest you grab an official release from this github project to get the latest update.
