### ISSUE TITLE
Rainbow hovering ABOVE default Windows Taskbar?

### ISSUE THREAD

**Issue by nkloney** [ad2017gd/RainbowTaskbar#29]
Not sure if this is just my computer, if this has something to do with the new update (**_2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5023706)_** or **_2023-03 .NET 6.0.15 Update for x64 Client (KB5024670)_**), or if I just need to re-login to my computer, but the rainbow now hovers ABOVE the taskbar instead of BEING the taskbar...
![image](https://user-images.githubusercontent.com/127987397/225412613-f65c791f-12e0-4168-836d-db2eddbd693c.png)

**Comment by ad2017gd** [comment]
last win11 update completely broke rnbtsk for what i can tell. will try to fix

**Comment by ad2017gd** [comment]
Fixed in 2.3.1 (e918aa5), probably
