### ISSUE TITLE
No color on taskbar? the opacity is too low.

### ISSUE THREAD

**Issue by GameIT-Official** [ad2017gd/RainbowTaskbar#31]
I no longer see the vivid rainbow colors on the taskbar. This happened after windows 11 update
![no color](https://user-images.githubusercontent.com/119961818/226548568-376cb020-21e3-4e96-a8c7-cbc4267edc14.png)

Also sometimes it hovers over the taskbar.

How much time will it take to fix?

**Comment by GameIT-Official** [comment]
Glad to hear that!
There was another RGB taskbar app I used before which also got broken, looks like microsoft re wrote the code for the task bar

**Comment by GameIT-Official** [comment]
Any updates??

**Comment by GameIT-Official** [comment]
Any updates??

**Comment by ad2017gd** [comment]
Haven't got to start fixing this yet. I have never worked with WinUI and I think its gonna be a pretty hard task for me. I am also busy learning for a coming exam so I don't really have an ETA for now.

**Comment by GameIT-Official** [comment]
Alr np take your time

**Comment by ad2017gd** [comment]
Fixed in 2.3.1 (e918aa5)
