### ISSUE TITLE
transparency does not work

### ISSUE THREAD

**Issue by Dalexxx** [ad2017gd/RainbowTaskbar#34]
I paid thinking it would work, but it doesn't

**Comment by ad2017gd** [comment]
where did you pay??? i dont sell this software anyhere :(

**Comment by ad2017gd** [comment]
anyways, known issue will have to make time to fix

**Comment by zCri** [comment]
bn

**Comment by zCri** [comment]
bn

**Comment by zCri** [comment]
numai sterge

**Comment by xAndrei166** [comment]
blud this software is free

**Comment by ad2017gd** [comment]
Fixed in 2.3.1 (e918aa5)
