### ISSUE TITLE
No option to undo Taskbar transparency?

### ISSUE THREAD

**Issue by kpcintegrations** [ad2017gd/RainbowTaskbar#44]
I applied transparency to the taskbar in Win 11, but there doesn't seem to be a way to revert it. I tried apply it at 100% and that didn't work, set style back to default, but that failed as well. Also it makes the pinned icons transparent as well, other wise it'd be fine the way it is. Can this be fixed?

**Comment by ad2017gd** [comment]
Hello, I've tried to replicate your issue but it works for me. Am I missing something?

https://github.com/ad2017gd/RainbowTaskbar/assets/39013925/49d932f6-361d-44c3-ab0a-29e686bf6667

**Comment by ad2017gd** [comment]
Did this happen after some Windows update, or since you started using this program?

**Comment by kpcintegrations** [comment]
It does not revert when exiting the program. But I managed to get it back to normal by setting the opacity to 99%. There must be some kind of bug about setting it 100%.

**Comment by kpcintegrations** [comment]
But Is there anyway to use this program without it making the pinned apps transparent as well?

**Comment by ad2017gd** [comment]
> It does not revert when exiting the program. But I managed to get it back to normal by setting the opacity to 99%. There must be some kind of bug about setting it 100%.

Just to verify, you are using the latest version from this GitHub, correct? There was indeed a bug with setting it to 99%, but it has been fixed.

**Comment by ad2017gd** [comment]
> But Is there anyway to use this program without it making the pinned apps transparent as well?

Not currently, but it could be possible in a future update.

**Comment by kpcintegrations** [comment]
I actually installed it via the windows store originally, but then used the exe from the releases page after the problem occurred. Might have been that combo. And awesome. It's an awesome program but with it making the icons transparent it's hard to tell them apart if they're similar. Thanks for the help.

**Comment by ad2017gd** [comment]
Just to confirm, does it work now, with the latest release?
