### ISSUE TITLE
not responding to change

### ISSUE THREAD

**Issue by AndrewAlkazeer** [ad2017gd/RainbowTaskbar#47]
Most of the time is not responding to a change of taskbar effects.

**Comment by ad2017gd** [comment]
i dont quite understand your issue. could you [fill out the bug report issue template](https://github.com/ad2017gd/RainbowTaskbar/issues/new?assignees=ad2017gd&labels=bug&projects=&template=bug_report.md&title=) and provide more info there?

**Comment by ad2017gd** [comment]
closed for inactivity
