### ISSUE TITLE
size issue

### ISSUE THREAD

**Issue by Matin11112** [ad2017gd/RainbowTaskbar#50]
the size of taskbar not same with  main  taskbar

**Comment by ad2017gd** [comment]
Can you send a screenshot?

**Comment by Matin11112** [comment]
I want to make it smaller.

**Comment by ad2017gd** [comment]
I cannot help you if you cannot provide more context. A screenshot of your taskbar would be great. Are you using scaling?
![image](https://github.com/ad2017gd/RainbowTaskbar/assets/39013925/524b76bb-7a75-47f4-8dc6-801eb6120563)

**Comment by Matin11112** [comment]
Is it what you are looking for?

**Comment by ad2017gd** [comment]
Was there supposed to be an attachment? I cannot see any image. Try uploading it to some image host first and send me the link.

**Comment by ad2017gd** [comment]
inactive
