### ISSUE TITLE
Second monitor ghosting upon wake up

### ISSUE THREAD

**Issue by Heika90** [ad2017gd/RainbowTaskbar#55]
In Windows 10, with 2 monitors, upon waking up from hibernation the second monitor has a ghosting duplicate of the RainbowTaskbar effect positioned directly above the taskbar.

![rainbowtaskbar-error](https://github.com/ad2017gd/RainbowTaskbar/assets/77622992/3a988d33-72b1-400c-bf36-f390db1f5137)

**Comment by ad2017gd** [comment]
Does it revert back if you apply & save again?

**Comment by ad2017gd** [comment]
inactive
